name: PR
on:
  pull_request:
  workflow_dispatch:
jobs:
  Fix:
    runs-on: arc-runner-set
    outputs:
      ref: ${{ steps.commit.outputs.commit_hash || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/jauntin/php-test-image:8.3
          options: -v ${{ github.workspace }}:/var/www/html
          run: |
            composer install &&
            vendor/bin/pint
      - id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
  Test:
    needs: [Fix]
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ needs.Fix.outputs.ref }}
